apiVersion: v1
kind: Service
metadata:
  name: randomstringgen-svc
  namespace: "bigapp-namespace"
spec:
  type: ClusterIP
  selector:
    app: randomstringgen
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
