apiVersion: v1
kind: Service
metadata:
  namespace: "bigapp-namespace"
  name: pingpongapp-svc
spec:
  type: ClusterIP
  selector:
    app: pingpongapp
  ports:
    - name: http
      port: 1234
      protocol: TCP
      targetPort: 3000
